[profile.default]
src = "contracts"
out = "forge-out"
libs = ["node_modules", "lib"]
test = "test"
cache_path = "forge-cache"

# Solidity compiler settings
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Gas settings
gas_limit = 30000000  # 30M gas limit for testing
gas_price = 20000000000

# RPC endpoints
[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
base_mainnet = "https://mainnet.base.org"
ethereum = "https://eth.llamarpc.com"

# Etherscan settings
[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }

# Fuzz testing settings
[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x1'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Invariant testing settings  
[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_run_limit = 5000
